image: Ubuntu

branches:
  only:
  - feature/app-veyor-deployment
  
services:
  - docker

stack: jdk 8

build_script:
- sh: ./mvnw --no-transfer-progress compile
- sh: ./mvnw --no-transfer-progress package -DskipTests

test_script:
- sh: ./mvnw --no-transfer-progress test surefire-report:report-only

on_success:
- sh: ls -l target
#TODO: change to latest when ready
- sh: docker build -f DockerfileUpload -t shayaantx/botdarr:custom
- sh: docker images

artifacts:
  - path: site/surefire-report.html
    name: Test Results