image: Ubuntu

services:
  - docker

stack: jdk 8

build_script:
- sh: ./mvnw --no-transfer-progress compile

test_script:
- sh: ./mvnw --no-transfer-progress test

package:
- sh: ./mvnw --no-transfer-progress package -DskipTests
