image: Ubuntu

services:
  - docker

stack: jdk 8

build_script:
- sh: ./mvnw --no-transfer-progress compile
- sh: ./mvnw --no-transfer-progress package -DskipTests

test_script:
- sh: ./mvnw --no-transfer-progress test